package com.example.ums;

public class Exam {
    public enum ExamType {
        QUIZ("quiz"),
        MIDTERM("midterm"),
        FINAL("final");

        private final String dbValue;

        ExamType(String dbValue) {
            this.dbValue = dbValue;
        }

        public String toDbValue() {
            return dbValue;
        }

        public static ExamType fromDbValue(String value) {
            if (value == null) {
                return null;
            }
            String v = value.trim().toLowerCase();
            for (ExamType t : values()) {
                if (t.dbValue.equals(v)) {
                    return t;
                }
            }
            return null;
        }
    }

    // exams table: examid (auto), examdate (varchar(10)), examtype (varchar(10)), courseid (int)
    private Integer examId;     // nullable when creating (auto-generated by DB)
    private Integer courseId;
    private String examDate;    // stored as String in DB (e.g., "YYYY-MM-DD")
    private ExamType examType;  // quiz / midterm / final

    public Exam(Integer examId, Integer courseId, String examDate, ExamType examType) {
        this.examId = examId;
        this.courseId = courseId;
        this.examDate = examDate;
        this.examType = examType;
    }

    /** Convenience constructor for inserts (no examId yet). */
    public Exam(Integer courseId, String examDate, ExamType examType) {
        this(null, courseId, examDate, examType);
    }

    public Integer getExamId() {
        return examId;
    }

    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    public Integer getCourseId() {
        return courseId;
    }

    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    public String getExamDate() {
        return examDate;
    }

    public void setExamDate(String examDate) {
        this.examDate = examDate;
    }

    public ExamType getExamType() {
        return examType;
    }

    public void setExamType(ExamType examType) {
        this.examType = examType;
    }
}
